Play travis
Otus-DevOps-2022-05/miv1989_infra pull request #2
Opened 2022-07-25 10:40 UTC by miv1989

2022-07-26 11:49 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил комментарий к файлу, дз возвращаю на доработку

2022-07-26 11:49 UTC, mrgreyves commented on .github/workflovs/auto-assign.yml
> +name: 'Auto Assign'
workfloW
у вас не корректно названа директория =)
нужно поправить =)

2022-08-07 05:56 UTC, miv1989 commented
Поправил, проверьте пожалуйста

2022-08-07 12:36 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь точно апрув =)

2022-08-10 05:05 UTC, merged